image: gradle:5.3.0-jdk11

build:
  stage: build
  script:
    - gradle build
  artifacts:
    reports:
      junit: build/test-results/test/TEST-*.xml

test-deploy:
  stage: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=codeplay-wallet-service-test --api-key=$HEROKU_API_KEY
  only:
    - master

prod-deploy:
  stage: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=codeplay-wallet-service --api-key=$HEROKU_API_KEY
  only:
    - master