server:
  port: 8082
  servlet:
    context-path: /api

spring:
  jpa:
    hibernate:
      ddl-auto: validate
      temp:
        use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}